# Generated by Django 5.2.8 on 2025-11-26 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del item (máximo 200 caracteres)', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del item (opcional)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del item')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el item está activo o deshabilitado')),
                ('propietario', models.ForeignKey(help_text='Usuario propietario del item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['propietario', '-fecha_creacion'], name='items_item_propiet_0d6470_idx'), models.Index(fields=['activo'], name='items_item_activo_f5d069_idx')],
            },
        ),
    ]
